<a href="https://colab.research.google.com/github/spyrosgaroufalis/TorchTest/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

!nvidia-smi

# hey


In [1]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cu128


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

torch.tensor creates tensor

In [3]:
scalar.ndim # shows dimensions (0)
scalar.item() # tensor back as python int

7

In [4]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
matrix[1]

tensor([ 9, 10])

In [8]:
matrix.shape

torch.Size([2, 2])

In [9]:
# TENSOR NOW
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

torch.Size([1, 3, 3])

#new


In [12]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6590, 0.8727, 0.3132, 0.5361],
        [0.8246, 0.5934, 0.4859, 0.1830],
        [0.9535, 0.8812, 0.3951, 0.8207]])

In [13]:
random_tensor.ndim

2

In [14]:
rand_tensor = torch.rand(size=(3, 244, 244))
# rand_tensor.ndim
zeros= torch.zeros(size=(3,4,5))
# zeros
ones= torch.ones(size=(3,4))
# ones
# ones.dtype


In [15]:
steps = torch.arange(start=0,end=1000, step=77)
torch.arange(0,10), steps

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924]))

TENSOR DATATYPE
TENSOR SHAPE
TENSOR DEVICE

In [16]:
more_zeros = torch.zeros_like(input= steps,
                              dtype=torch.float16, # tensor datatype(32 is default)
                              device=None, # "cuda" , what dev is your tensor
                              requires_grad=False) # if you want torch to track gradients of a tensor when it goes to sum calculations
# more_zeros
# more_zeros.dtype
# change type
more_zeros16ver = more_zeros.type(torch.float32)
# more_zeros16ver.dtype
print(more_zeros16ver)
print(f"type: {more_zeros16ver.dtype}")
print(f"shape: {more_zeros16ver.shape}") # h to function size(), to shape einai attribute
print(f"device: {more_zeros16ver.device}")

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
type: torch.float32
shape: torch.Size([13])
device: cpu


PRAKSEIS

In [17]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [18]:
tensor * 10
# h torch.mul(tensor, 10)

tensor([10, 20, 30])

In [19]:
tensor - 10

tensor([-9, -8, -7])

Matrixsx

In [20]:
print(tensor * tensor)

tensor([1, 4, 9])


In [21]:
print(torch.matmul(tensor, tensor))
# matrix multiplication by hand prosthetei epipleon

tensor(14)


In [22]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 685 µs, sys: 720 µs, total: 1.41 ms
Wall time: 3.57 ms


In [23]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 663 µs, sys: 111 µs, total: 774 µs
Wall time: 622 µs


tensor(14)

In [24]:
# same as:
%%time
tensor @ tensor

CPU times: user 313 µs, sys: 52 µs, total: 365 µs
Wall time: 315 µs


tensor(14)

**INNER DIMENSIONS MUST MATCH**: (3,2)@(3,2) WONT WORK, (2,3)@(3,2) WILL WORK, (3,2)@(2,3) will work

In [25]:
a = torch.rand([2,3])
b = torch.rand([3,2])
a @ b
# h
# torch.matmul(torch.rand(3,2), torch.rand(3,2))

tensor([[0.6005, 1.0408],
        [0.3632, 0.7555]])

RESULT MATRIX HAS SHAPE OF THE **OUTER DIMENSIONS**

**MATMUL IS ALSO TORCH.MM**

**TO FIX TENSOR DIMENSIONS USE TRANSPOSE**


In [26]:
c = torch.tensor([[7,10],
               [8,10],
               [9,12]])
e = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])
# torch.mm(c, e)
# now we use transpose to manipulate shape of one tensor



**TRANSPOSE SWITCHES THE AXES OF DIMENSIONS OF THE TENSOR**


In [27]:
e.T, e.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [28]:
torch.matmul(c, e.T)

tensor([[ 27,  61,  95],
        [ 28,  64, 100],
        [ 33,  75, 117]])

In [29]:
torch.min(e)
# torch.mean(e)
torch.mean(e.type(torch.float32)) # calc the mean average of the tensor
# or
e.type(torch.float32).mean()


tensor(3.5000)

In [30]:
torch.sum(e)
# e.sum()

tensor(21)

In [31]:
e.argmin() # which index has the min
e.argmax()
# e[0]

tensor(5)

In [32]:
h = torch.arange(1., 11.)
# h = tensor ([1., 2., 3....9.])
h = h.reshape(1,10)
h = h.reshape(10,1)


**RESHAPING CAN BE DONE AS LONG AS DIMENSION MULTIPLICATION IS THE SAME AS THE START DIMENSIONS**

In [33]:
h = h.reshape(5,2)
h
# 5* 2 = 10 ara ginetai

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [34]:
y = h.view(1,10)


**VIEW SHAES SAME MEMORY AS ORIGIN, IT BASICALLY IS THE SAME**

In [35]:
y_stacked = torch.stack([y, y, y, y], dim=2)
y_stacked

tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]])

**SQUEEZE REMOVES ALL SINGLE DIMENSIONS(1)**

In [36]:
y_stacked = y_stacked.squeeze()
y_stacked, y_stacked.shape
y_stacked.unsqueeze(dim=0)

tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]])

**PERMUTE REARANGES DIMENSIONS**

In [39]:
x_origin= torch.rand(size=(224, 224, 3)) # height, width , colour channels
# permute
x_perm = x_origin.permute(2, 0, 1)
x_perm.shape

torch.Size([3, 224, 224])

**PERMUTE IS A VIEW**


In [50]:
x_perm[:,0,0]

tensor([0.3751, 0.0573, 0.6153])