<a href="https://colab.research.google.com/github/spyrosgaroufalis/TorchTest/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

!nvidia-smi

# hey


In [ ]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cu128


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

torch.tensor creates tensor

In [ ]:
scalar.ndim # shows dimensions (0)
scalar.item() # tensor back as python int

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR NOW
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

#new


In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6590, 0.8727, 0.3132, 0.5361],
        [0.8246, 0.5934, 0.4859, 0.1830],
        [0.9535, 0.8812, 0.3951, 0.8207]])

In [ ]:
random_tensor.ndim

2

In [ ]:
rand_tensor = torch.rand(size=(3, 244, 244))
# rand_tensor.ndim
zeros= torch.zeros(size=(3,4,5))
# zeros
ones= torch.ones(size=(3,4))
# ones
# ones.dtype


In [ ]:
steps = torch.arange(start=0,end=1000, step=77)
torch.arange(0,10), steps

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924]))

TENSOR DATATYPE
TENSOR SHAPE
TENSOR DEVICE

In [ ]:
more_zeros = torch.zeros_like(input= steps,
                              dtype=torch.float16, # tensor datatype(32 is default)
                              device=None, # "cuda" , what dev is your tensor
                              requires_grad=False) # if you want torch to track gradients of a tensor when it goes to sum calculations
# more_zeros
# more_zeros.dtype
# change type
more_zeros16ver = more_zeros.type(torch.float32)
# more_zeros16ver.dtype
print(more_zeros16ver)
print(f"type: {more_zeros16ver.dtype}")
print(f"shape: {more_zeros16ver.shape}") # h to function size(), to shape einai attribute
print(f"device: {more_zeros16ver.device}")

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
type: torch.float32
shape: torch.Size([13])
device: cpu


PRAKSEIS

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10
# h torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

Matrixsx

In [ ]:
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
print(torch.matmul(tensor, tensor))
# matrix multiplication by hand prosthetei epipleon

tensor(14)


In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 685 µs, sys: 720 µs, total: 1.41 ms
Wall time: 3.57 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 663 µs, sys: 111 µs, total: 774 µs
Wall time: 622 µs


tensor(14)

In [ ]:
# same as:
%%time
tensor @ tensor

CPU times: user 313 µs, sys: 52 µs, total: 365 µs
Wall time: 315 µs


tensor(14)

**INNER DIMENSIONS MUST MATCH**: (3,2)@(3,2) WONT WORK, (2,3)@(3,2) WILL WORK, (3,2)@(2,3) will work

In [ ]:
a = torch.rand([2,3])
b = torch.rand([3,2])
a @ b
# h
# torch.matmul(torch.rand(3,2), torch.rand(3,2))

tensor([[0.6005, 1.0408],
        [0.3632, 0.7555]])

RESULT MATRIX HAS SHAPE OF THE **OUTER DIMENSIONS**

**MATMUL IS ALSO TORCH.MM**

**TO FIX TENSOR DIMENSIONS USE TRANSPOSE**


In [ ]:
c = torch.tensor([[7,10],
               [8,10],
               [9,12]])
e = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])
# torch.mm(c, e)
# now we use transpose to manipulate shape of one tensor



**TRANSPOSE SWITCHES THE AXES OF DIMENSIONS OF THE TENSOR**


In [ ]:
e.T, e.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(c, e.T)

tensor([[ 27,  61,  95],
        [ 28,  64, 100],
        [ 33,  75, 117]])

In [ ]:
torch.min(e)
# torch.mean(e)
torch.mean(e.type(torch.float32)) # calc the mean average of the tensor
# or
e.type(torch.float32).mean()


tensor(3.5000)

In [ ]:
torch.sum(e)
# e.sum()

tensor(21)

In [ ]:
e.argmin() # which index has the min
e.argmax()
# e[0]

tensor(5)

In [ ]:
h = torch.arange(1., 11.)
# h = tensor ([1., 2., 3....9.])
h = h.reshape(1,10)
h = h.reshape(10,1)


**RESHAPING CAN BE DONE AS LONG AS DIMENSION MULTIPLICATION IS THE SAME AS THE START DIMENSIONS**

In [ ]:
h = h.reshape(5,2)
h
# 5* 2 = 10 ara ginetai

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
y = h.view(1,10)


**VIEW SHAES SAME MEMORY AS ORIGIN, IT BASICALLY IS THE SAME**

In [ ]:
y_stacked = torch.stack([y, y, y, y], dim=2)
y_stacked

tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]])

**SQUEEZE REMOVES ALL SINGLE DIMENSIONS(1)**

In [ ]:
y_stacked = y_stacked.squeeze()
y_stacked, y_stacked.shape
y_stacked.unsqueeze(dim=0)

tensor([[[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]])

**PERMUTE REARANGES DIMENSIONS**

In [ ]:
x_origin= torch.rand(size=(224, 224, 3)) # height, width , colour channels
# permute
x_perm = x_origin.permute(2, 0, 1)
x_perm.shape

torch.Size([3, 224, 224])

**PERMUTE IS A VIEW(SHARES MEMORY)**


In [ ]:
x_perm[:,0,0]

tensor([0.3751, 0.0573, 0.6153])

In [3]:
import torch
import numpy as np

# numpy creates with default datatype float64
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

**TO REDUCE RANDOMNESS, USE RANDOM SEED( WORKS FOR 1 LINE OF CODE)**

In [5]:
random1 = torch.rand(3,3)
random2 = torch.rand(3,3)
print(random1 == random2)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [8]:
# set random seed
random_seed = 42
torch.manual_seed(random_seed)

random3 = torch.rand(3,4)
# need to redo it
torch.manual_seed(random_seed)
random4 = torch.rand(3,4)
print(random3 == random4)
#

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [13]:
# !nvidia-smi
import torch
torch.cuda.is_available()

True

**BE DEVICE AGNOSTIC**

In [15]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

**PUTTING TENSORS ON GPU**

**DEFAULT IS ON CPU WHEN CREATING**

In [17]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [18]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [21]:
# OVING BACK TO CPU?
# why? some code dont work if on gpu, .numpy() for example
tensor_cpu = tensor_gpu.cpu()
tensor_cpu.device

device(type='cpu')

**TORCHN.NN ( NEURAL NETWORK) CONTAINS EVERYTHING WE NEED**

**LINEAR REGRESSION formula= Yi= f(Xi,b)+ei , GENERAL FORM IS Y=a+bX -> X IS EXPLANATORY VAR AND Y IS DEPENDENT VAR**

In [23]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# check
torch.__version__

'2.11.0+cu128'

In [24]:
# creating known parameters
weight = 0.7 # equivalent to b
bias = 0.3 # equivalent to a

start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1) # input
y = weight*X+bias # output

X[:10], y[:10]


(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

**TRAINING-VALIDATING-TESTING SETS**

**70% - 15 % - 15% OR 80-20 MOSTLY**