<a href="https://colab.research.google.com/github/spyrosgaroufalis/TorchTest/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

!nvidia-smi

# hey


In [4]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cu128


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

torch.tensor creates tensor

In [8]:
scalar.ndim # shows dimensions (0)
scalar.item() # tensor back as python int

7

In [10]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
matrix.shape

torch.Size([2, 2])

In [17]:
# TENSOR NOW
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
#new